export const Data = [
  {
    productURL: "/quick-baker",
    imageURL: "/addons/images/quick-baker/thumb.png",
    title: "Quick Baker",
    price: "$36 - $360",
    info: "Baking",
  },
  {
    productURL: "/megascans-bridge",
    imageURL: "/addons/images/megascans-bridge/thumb.png",
    title: "Megascans Bridge v2",
    price: "$20 - $200",
    info: "Object",
  },
  {
    productURL: "/quick-measure",
    imageURL: "/addons/images/quick-measure/thumb.png",
    title: "Quick Measure v2",
    price: "$20 - $200",
    info: "3D View",
  },
  {
    productURL: "/knife-circle",
    imageURL: "/addons/images/knife-circle/thumb.png",
    title: "Knife Circle",
    price: "$20 - $200",
    info: "Mesh",
  },
  {
    productURL: "/quick-decal",
    imageURL: "/addons/images/quick-decal/thumb.png",
    title: "Quick Decal",
    price: "$20 - $200",
    info: "Material",
  },
  {
    productURL: "/quick-interface",
    imageURL: "/addons/images/quick-interface/thumb.png",
    title: "Quick Interface",
    price: "$10 - $100",
    info: "Interface",
  },
  {
    productURL: "/camera-preview",
    imageURL: "/addons/images/camera-preview/thumb.png",
    title: "Camera Preview",
    price: "$10 - $100",
    info: "3D View",
  },
  {
    productURL: "/quick-theme",
    imageURL: "/addons/images/quick-theme/thumb.png",
    title: "Quick Theme",
    price: "$10 - $100",
    info: "Interface",
  },
  {
    productURL: "/quick-replace",
    imageURL: "/addons/images/quick-replace/thumb.png",
    title: "Quick Replace",
    price: "$10 - $100",
    info: "Object",
  },
  {
    productURL: "/blender-to-unity",
    imageURL: "/addons/images/blender-to-unity/thumb.png",
    title: "Blender to Unity",
    price: "$30 - $300",
    info: "Export",
  },
  {
    productURL: "/blender-to-unreal",
    imageURL: "/addons/images/blender-to-unreal/thumb.png",
    title: "Blender to Unreal",
    price: "$30 - $300",
    info: "Export",
  },
  {
    productURL: "/blender-to-godot",
    imageURL: "/addons/images/blender-to-godot/thumb.png",
    title: "Blender to Godot",
    price: "$20 - $200",
    info: "Export",
  },
  {
    productURL: "/blender-to-game-engine",
    imageURL: "/addons/images/blender-to-game-engine/thumb.png",
    title: "Blender to Game Engine (Unity, Unreal & Godot) Bundle",
    price: "$50 - $500",
    info: "Export",
  },
];
