export const Data = [
  {
    productURL: "/quick-baker",
    imageURL: "./images/quick-baker/thumb.png",
    title: "Quick Baker",
    price: "$36 - $360",
    info: "Baking",
  },
  {
    productURL: "/quick-decal",
    imageURL: "./images/quick-decal/thumb.png",
    title: "Quick Decal",
    price: "$20 - $200",
    info: "Material",
  },
  {
    productURL: "/quick-measure",
    imageURL: "./images/quick-measure/thumb.png",
    title: "Quick Measure",
    price: "$20 - $200",
    info: "3D View",
  },
  {
    productURL: "/quick-interface",
    imageURL: "./images/quick-interface/thumb.png",
    title: "Quick Interface",
    price: "$10 - $100",
    info: "Interface",
  },
  {
    productURL: "/quick-theme",
    imageURL: "./images/quick-theme/thumb.png",
    title: "Quick Theme",
    price: "$10 - $100",
    info: "Interface",
  },
  {
    productURL: "/camera-preview",
    imageURL: "./images/camera-preview/thumb.png",
    title: "Camera Preview",
    price: "$10 - $100",
    info: "3D View",
  },
  {
    productURL: "/blender-to-unity",
    imageURL: "./images/blender-to-unity/thumb.png",
    title: "Blender to Unity",
    price: "$30 - $300",
    info: "Export",
  },
  {
    productURL: "/blender-to-unreal",
    imageURL: "./images/blender-to-unreal/thumb.png",
    title: "Blender to Unreal",
    price: "$30 - $300",
    info: "Export",
  },
  {
    productURL: "/blender-to-game-engine",
    imageURL: "./images/blender-to-game-engine/thumb.png",
    title: "Blender to Game Engine (Unity & Unreal) Bundle",
    price: "$50 - $500",
    info: "Export",
  },
  {
    productURL: "/quick-replace",
    imageURL: "./images/quick-replace/thumb.png",
    title: "Quick Replace",
    price: "$10 - $100",
    info: "Object",
  },
];
